### ISSUE TITLE
Feature Request: Make window size depending on screen resolution

### ISSUE THREAD

**Issue by Zoldyako** [brain-child/moobo#13]
My notebook has a resolution of 1366x768 (HD) and the app don't fit in the entire screen

**Comment by pierrefabarius** [comment]
Thank you for the report. This is a more general problem, which I want to tackle in the future.

**Comment by NathanBnm** [comment]
Would be great, here is how it renders on my laptop screen:

![Capture d'écran du 2021-11-10 11 28 31](https://user-images.githubusercontent.com/45366162/141097692-13ace013-c18e-4a45-8936-f8835b909dd9.png)

**Comment by pierrefabarius** [comment]
I did change the title, because the issue relates more to the problem that the window does not fully fit on your screen. And this is different to let the user resize the window.

For now, I implemented a way to solve your issue. It will be published in the next release. One thing to solve is that some widgets from the demo board (and other boards as well) are placed outside the board for smaller screens like yours. Theoretically there are different approaches to change that. The easiest would be to drop the demo board at all and another is to calculate the coordinates of the widgets.

However, a solution will be found soon.

**Comment by ChildishGiant** [comment]
Or to allow for the board to be scrolled (or even zoomed)

**Comment by pierrefabarius** [comment]
@ChildishGiant That is the plan in the future. Normally one would simply add a ```Gtk.ScrolledWindow```, but in connection with the Gtk.Overlay this is not that simple. I think the problem is, that the widgets placed on each overlay-layer do not communicate their position to the ScrolledWindow. So the ScrolledWindow does not know when to add scrollbars or not. A work around would be to update the ScrolledWindow manually with each movement of a widget. Using the ScrolledWindow would solve the resizing problem of the app window.

Another approach, could be [this](https://blakerain.com/blog/overlays-with-custom-widgets-in-gtk).

**Comment by ChildishGiant** [comment]
Maybe it'd be worth having a look at how Akira implemented their canvas. I had a quick crack at it the other night but ran into the issues you've mentioned.

**Comment by pierrefabarius** [comment]
@ChildishGiant I looked into the implementation of Akira too, but I honestly had no clue how it was functioning. I tend to take the approach of the link I posted. It will may take some time though. Scrolling and zooming is what I plan for version 1.0.0.

Let's cut the discussion for now. This issue might not be the best place for that. I suggest to open a new issue.

**Comment by pierrefabarius** [comment]
@Zoldyako solved with version 0.1.2
