### ISSUE TITLE
[Enhancement] Show placeholder 'image' icon

### ISSUE THREAD

**Issue by kdwk** [brain-child/moobo#8]
When the user double clicks to add an image, the location where they double click should have an 'image' icon as a placeholder so the user knows where the image will be added

**Comment by pierrefabarius** [comment]
I like that idea. Thank you!

**Comment by pierrefabarius** [comment]
@kdwk how about this?

https://user-images.githubusercontent.com/29637548/142029499-4040daf9-f7be-47d6-b4b6-e263b1e7cb97.mp4

**Comment by kdwk** [comment]
@pierrefabarius I’m not sure about this. elementary OS uses this icon to mean ‘unavailable’. There are already frequently seen when AppCenter cannot load app icons. I think a better approach would be to use the MIME type icons for images provided by the elementary icon pack.

**Comment by pierrefabarius** [comment]
@kdwk On double-click, there is no image, since the user needs to select one. That's why I'm currently using the missing-image-icon. 

You probably mean this icon, right?:
![image](https://user-images.githubusercontent.com/29637548/142259412-4fc64aa3-8816-48b9-926b-f3b51dd6afb7.png)

I agree, that it may looks better than that gray-scale icon.

https://user-images.githubusercontent.com/29637548/142260911-6bc22983-b497-47b4-ab93-c82cd8398b66.mp4

**Comment by kdwk** [comment]
Placeholder icon looks good! Use the filechooser portal for selecting files as well, and it’s good to go.

**Comment by pierrefabarius** [comment]
Filechooser portal is already in use. 
The feature will be part of the next release. I close the issue now.
